version: '3'
services:
  api:
    env_file:
      - ./.env
    image: piotrostr/api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    command: gunicorn src.app.app:app
    build: .
