version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx
  api:
    environment:
      - INFURA_KEY=$INFURA_KEY
      - CHAIN=rinkeby
    build: .
    image: piotrostr/smplverse-api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    command: python main.py
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
