version: '3'

services:
  api:
    build: .
    image: piotrostr/smplverse-api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    command: python main.py
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
