version: '3'

services:
  proxy:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx
  api_cpu:
    build: .
    image: piotrostr/smplverse-api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    command: gunicorn -b "0.0.0.0:5000" main:app
  api:
    extends:
      service: api_cpu
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
