version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx
  api:
    env_file:
      - ./.env
    image: piotrostr/api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
      - ~/.aws:/root/.aws
    ports:
      - 5000:5000
    command: gunicorn src.app.app:app
    build: .
