version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx
  api:
    environment:
      - INFURA_KEY=$INFURA_KEY
      - CONTRACT_ADDRESS_RINKEBY=$CONTRACT_ADDRESS_RINKEBY
      - CHAIN=rinkeby
      - IPFS_ENDPOINT=$IPFS_ENDPOINT
      - IPFS_PROJECT_ID=$IPFS_PROJECT_ID
      - IPFS_PROJECT_SECRET=$IPFS_PROJECT_SECRET
    env_file: 
      - ./.env
    build: .
    image: piotrostr/smplverse-api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    # command: gunicorn src.app.app:app
    command: python main.py
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
