version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
  api:
    env_file:
      - ./.env
    image: piotrostr/api
    container_name: api
    platform: linux/amd64
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    command: gunicorn src.app.app:app
    build: .
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
